# Robinhood HA Breakout Configuration

# Trading Parameters
CONTRACT_QTY: 1
LOOKBACK_BARS: 20
MODEL: "gpt-4o-mini"  # Options: "gpt-4o-mini", "deepseek-chat"

# Bankroll Management
START_CAPITAL: 500.0         # USD - Minimum realistic amount for SPY options
RISK_FRACTION: 0.20          # max % of bankroll you may risk per trade
SIZE_RULE: "dynamic-qty"       # Options: "fixed-qty", "dynamic-qty"
BANKROLL_FILE: "bankroll.json"
POSITIONS_FILE: "positions.csv"  # Position tracking ledger

# Market Data
SYMBOL: "SPY"
TIMEFRAME: "5m"
DATA_SOURCE: "yfinance"      # Options: "yfinance", "alpaca"

# Browser Settings
HEADLESS: false
IMPLICIT_WAIT: 10
PAGE_LOAD_TIMEOUT: 30

# Risk Management
MAX_PREMIUM_PCT: 0.50        # Max premium as % of bankroll
MIN_CONFIDENCE: 0.35         # Minimum LLM confidence to trade
IV_THRESHOLD: 45.0           # Implied volatility threshold
MIN_CANDLE_BODY_PCT: 0.10    # Minimum breakout-candle body as % of price

# Intraday Trading Settings
PROFIT_TARGET_PCT: 0.15      # Take profit at 15% gain (conservative)
STOP_LOSS_PCT: 0.25          # Stop loss at 25% loss
EOD_CLOSE_TIME: "15:45"      # Close all positions by 3:45 PM ET
MONITOR_INTERVAL: 2          # Check positions every 2 minutes
MIN_PROFIT_THRESHOLD: 0.05   # Minimum 5% profit to consider selling




# Logging
LOG_LEVEL: "INFO"
LOG_FILE: "logs/app.log"
TRADE_LOG_FILE: "logs/trade_log.csv"
MAX_LOG_SIZE_MB: 5
LOG_BACKUP_COUNT: 3

# Timing
MARKET_OPEN_HOUR: 9
MARKET_OPEN_MINUTE: 30
MARKET_CLOSE_HOUR: 16
MARKET_CLOSE_MINUTE: 0
