# Robinhood HA Breakout Configuration

# Broker & Environment Configuration (v0.9.0)
BROKER: "alpaca"            # allowed: "alpaca" | "robinhood"
ALPACA_ENV: "live"              # allowed: "paper" | "live" (default: paper)
ALPACA_PAPER_BASE_URL: "https://paper-api.alpaca.markets"
ALPACA_LIVE_BASE_URL: "https://api.alpaca.markets"
ALPACA_KEY_ID: "<env:ALPACA_KEY_ID>"
ALPACA_SECRET_KEY: "<env:ALPACA_SECRET_KEY>"
START_CAPITAL_DEFAULT: 500      # seed for new ledgers if none exist

# Trading Parameters
CONTRACT_QTY: 1
LOOKBACK_BARS: 20
MODEL: "gpt-4o-mini"  # Options: "gpt-4o-mini", "deepseek-chat"

# Ensemble LLM Configuration (v0.6.0)
ENSEMBLE_ENABLED: true       # master toggle for two-model ensemble
ENSEMBLE_MODELS:
  - gpt-4o-mini
  - deepseek-chat

# Chrome Driver Configuration (v0.6.1)
CHROME_MAJOR: 131            # Chrome major version; null = auto-detect

# Bankroll Management
START_CAPITAL: 150.0         # USD - Minimum realistic amount for SPY options
RISK_FRACTION: 0.90          # max % of bankroll you may risk per trade -- allows up to $135 per trade for QQQ
SIZE_RULE: "fixed-qty"       # Options: "fixed-qty", "dynamic-qty"
BANKROLL_FILE: "bankroll.json"
# POSITIONS_FILE: "positions.csv"  # Position tracking ledger (commented out to use scoped files)

# Memory / Dealer Gamma
MEMORY_DEPTH: 5  # Number of recent trades to include in LLM context
GAMMA_FEED_PATH: "data/spotgamma_dummy.csv"  # Path to SpotGamma CSV cache

# Market Data
SYMBOLS: ["SPY", "QQQ", "IWM", "UVXY", "TLT", "GLD", "DIA", "XLK", "XLF", "XLE"]
# SYMBOLS: ["SPY", "QQQ", "IWM", "UVXY", "TLT", "GLD", "SMH", "XLK", "XLF", "XLE", "DIA", "AAPL", "AMD", "USO", "SLV", "F", "PLTR", "AAL", "SNAP"]  # Enhanced multi-symbol support
SYMBOL: "SPY"                    # Default/fallback symbol for backwards compatibility
TIMEFRAME: "5m"
DATA_SOURCE: "alpaca"      # Options: "yfinance", "alpaca"

# Multi-Symbol Configuration
multi_symbol:
  enabled: true                   # Enable multi-symbol scanning
  max_concurrent_trades: 1        # Maximum trades across all symbols
  symbol_allocation: "equal"      # Options: "equal", "weighted", "priority"
  scan_interval_seconds: 60       # Reduced from 120s to 60s for rapid breakout detection
  # Scan priority (top gets first fill attempts when budget is tight)
  priority_order: ["SPY", "QQQ", "AAPL", "TLT", "GLD", "IWM", "AMD", "SMH", "XLF", "XLK", "USO", "SLV", "F", "PLTR", "UVXY", "DIA", "AAL", "SNAP"]

# Browser Settings
HEADLESS: false
IMPLICIT_WAIT: 10
PAGE_LOAD_TIMEOUT: 30

# Risk Management
MAX_PREMIUM_PCT: .70        # Max premium as % of bankroll (conservative) -- default: 0.50,0.35
MIN_CONFIDENCE: 0.65         # Minimum LLM confidence to trade (conservative)
IV_THRESHOLD: 45.0           # Implied volatility threshold
MIN_CANDLE_BODY_PCT: 0.05    # Minimum breakout-candle body as % of price (lowered for sensitivity)
MIN_TR_RANGE_PCT: 1.0        # Minimum true range percentage for trade entry (volatility filter)

# Per-Symbol True Range Thresholds (allows trading in calm market conditions)
MIN_TR_RANGE_PCT_BY_SYMBOL:
  SPY: 0.10
  QQQ: 0.15
  IWM: 0.20
  XLF: 0.15
  XLK: 0.20
  DIA: 0.15
  GLD: 0.10
  TLT: 0.10
  UVXY: 0.60
  XLE: 0.20

# Intraday Trading Settings
PROFIT_TARGET_PCT: 0.15      # Take profit at 15% gain (conservative)
STOP_LOSS_PCT: 0.25          # Stop loss at 25% loss
EOD_CLOSE_TIME: "15:45"      # Close all positions by 3:45 PM ET
MONITOR_INTERVAL: 2          # Check positions every 2 minutes
MIN_PROFIT_THRESHOLD: 0.05   # Minimum 5% profit to consider selling

# Advanced Exit Strategies (Priority 2)
exit_strategies:
  # Trailing Stop Configuration
  trailing_stop_enabled: true
  trailing_stop_activation_pct: 10.0    # Start trailing after 10% profit
  trailing_stop_distance_pct: 5.0       # Trail 5% behind peak profit
  
  # Time-Based Exit Configuration
  time_based_exit_enabled: true
  market_close_time: "15:45"             # Close all positions by 3:45 PM ET
  warning_minutes_before_close: 15      # Alert 15 minutes before close
  
  # Profit Target Laddering
  profit_targets: [15.0, 25.0, 35.0, 50.0, 75.0, 100.0, 150.0, 200.0]   # Alert at these profit levels (%)
  
  # Stop Loss Configuration
  stop_loss_pct: 25.0                   # Traditional stop loss at 25% loss
  
  # Exit Strategy Priorities (order matters)
  # 1. Trailing stop (dynamic profit protection)
  # 2. Time-based exit (avoid overnight risk)
  # 3. Traditional stop loss (capital protection)
  # 4. Profit targets (informational alerts)

# Alpaca Options Configuration
alpaca:
  # Global spread and liquidity guards
  max_spread_pct: 8               # Maximum bid-ask spread as % of mid price
  max_spread_abs: 0.10            # Maximum absolute bid-ask spread ($)
  
  # Enhanced breakout detection for rapid moves (QQQ PUT fix)
  rapid_move_threshold: 0.5       # Trigger analysis on >0.5% moves in 5min
  volume_spike_multiplier: 1.5    # Volume must be 1.5x average for rapid moves
  breakout_sensitivity: "high"    # Options: "low", "medium", "high"
  
  # Symbol-specific minimum open interest requirements
  min_open_interest:
    default: 10000                # Default minimum for unlisted symbols
    SPY: 20000                    # Highest liquidity ETF
    QQQ: 2000                     # Tech ETF (adjusted for 0DTE reality)
    IWM: 10000                    # Small cap ETF
    AAPL: 10000                   # Blue chip stock
    AMD: 8000                     # Tech stock
    SMH: 1500                     # Semiconductor ETF (adjusted for very low liquidity)
    TLT: 8000                     # Treasury ETF
    GLD: 8000                     # Gold ETF
    XLK: 6000                     # Technology sector ETF
    XLF: 6000                     # Financial sector ETF
    XLE: 6000                     # Energy sector ETF
    USO: 6000                     # Oil ETF
    SLV: 6000                     # Silver ETF
    DIA: 6000                     # Dow Jones ETF
    F: 5000                       # Ford stock
    PLTR: 5000                    # Palantir stock
    UVXY: 5000                    # Volatility ETF
    AAL: 4000                     # American Airlines stock
    SNAP: 4000                    # Snapchat stock
  
  # Options expiry policy per symbol (0DTE vs WEEKLY)
  expiry_policy:
    default: "WEEKLY"             # Default to weekly options for better liquidity
    SPY: "0DTE"                   # SPY has excellent 0DTE liquidity
    QQQ: "0DTE"                   # QQQ has good 0DTE liquidity
    AAPL: "0DTE"                  # AAPL has decent 0DTE liquidity
    XLE: "WEEKLY"                 # XLE better with weekly options
    XLF: "WEEKLY"                 # Financial sector better with weekly
    XLK: "WEEKLY"                 # Tech sector better with weekly
    IWM: "WEEKLY"                 # Small cap better with weekly

# Logging
LOG_LEVEL: "INFO"
LOG_FILE: "logs/app.log"
TRADE_LOG_FILE: "logs/trade_log.csv"
MAX_LOG_SIZE_MB: 5
LOG_BACKUP_COUNT: 3

# Timing
MARKET_OPEN_HOUR: 9
MARKET_OPEN_MINUTE: 30
MARKET_CLOSE_HOUR: 16
MARKET_CLOSE_MINUTE: 0

# Slack UX Configuration (v0.7.0)
HEARTBEAT_EVERY: 3  # Send heartbeat every N scan intervals to avoid spam



# CHROME_MAJOR: 138
